package Vistas;

//IMPORTS
import tema7_pract1_ejer3.*;
import javax.swing.JOptionPane;

/**
 *
 * @author MIGUEL
 */
public class Venta extends javax.swing.JFrame {

    /**
     * Creates new form Compra
     */
    public Venta() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        jLok.setVisible(false);
        jLfallo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTproducto = new javax.swing.JTextField();
        jTunidades = new javax.swing.JTextField();
        jTimporte = new javax.swing.JTextField();
        jBvolver = new javax.swing.JButton();
        jBcomprar = new javax.swing.JButton();
        jLok = new javax.swing.JLabel();
        jLfallo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 24)); // NOI18N
        jLabel1.setText("VENTAS");

        jLabel2.setText("Producto");

        jLabel3.setText("Unidades");

        jLabel4.setText("Importe");

        jTproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTproductoActionPerformed(evt);
            }
        });

        jTunidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTunidadesActionPerformed(evt);
            }
        });

        jTimporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTimporteActionPerformed(evt);
            }
        });

        jBvolver.setText("VOLVER");
        jBvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvolverActionPerformed(evt);
            }
        });

        jBcomprar.setText("COMPRAR");
        jBcomprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcomprarActionPerformed(evt);
            }
        });

        jLok.setForeground(new java.awt.Color(0, 102, 0));
        jLok.setText("Venta Verificada ");

        jLfallo.setForeground(new java.awt.Color(204, 0, 0));
        jLfallo.setText("Venta Fallida");

        jLabel5.setForeground(new java.awt.Color(153, 153, 0));
        jLabel5.setText("ENTER");

        jLabel6.setForeground(new java.awt.Color(153, 153, 0));
        jLabel6.setText("ENTER");

        jLabel7.setForeground(new java.awt.Color(153, 153, 0));
        jLabel7.setText("CLICK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBvolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTimporte, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTunidades)
                                    .addComponent(jTproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBcomprar)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLfallo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLok, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTunidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTimporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcomprar)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLfallo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jBvolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTproductoActionPerformed
        // ENTER PRODUCTO
        try {

            //PRIMERA COMPROBACION SI EL CAMPO PRODUCTO ESTA VACIO
            if (jTproducto.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Se requiere un producto.");
            } else {

                //SIEMPRE SE REQUIERE BUSCAR EL PRODUCTO
                boolean encontradoProducto = Controladora.buscarProducto(jTproducto.getText().toLowerCase());

                //COMPRUEBO SI ES CIERTA LA BUSQUEDA
                if (encontradoProducto == true) {
                    /*SI LO ES PARA VENDER, NECESITO SABER LA CANTIDAD DISPONIBLE A LA VENTA
                    POR ESO AHORA LE DIGO A LA CONTROLADORA QUE ME FACILITE DICHA CANTIDAD*/
                    String disponibilidad = Controladora.comprobarDisponilibilidad();
                    /*HAGO EL PARSE A DOUBLE PARA PODER COMPARAR ESA CANTIDAD NUMERICA CON EL VALOR 0
                    SI ES 0, NO TENGO EXISTENCIAS*/
                    if (Double.parseDouble(disponibilidad) > 0) {
                        //MUESTRO EL NUMERO DE EXISTENCIAS SI SE DA EL CASO
                        JOptionPane.showMessageDialog(this, "Hay " + disponibilidad + " existencias");
                    } else {
                        //SI NO HAY EXISTENCIAS, MUESTRO AVISADORES Y MENSAJE
                        jLfallo.setVisible(true);
                        JOptionPane.showMessageDialog(this, "No hay existencias");
                        jLfallo.setVisible(false);
                        resetearCampos();
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error desconocido al buscar producto");
        }

    }//GEN-LAST:event_jTproductoActionPerformed

    private void jTunidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTunidadesActionPerformed
        // ENTER UNIDADES

        try {
            if (jTunidades.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Introduce las unidades");
            } else {
                boolean ok = Controladora.comprobarUnidades(jTunidades.getText());

                if (ok) {
                    Double importe = Controladora.calcularImporte(jTunidades.getText());
                    jTimporte.setText(importe.toString());
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error desconocido al buscar unidades");
        }

    }//GEN-LAST:event_jTunidadesActionPerformed

    private void jBvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvolverActionPerformed
        // VOTON VOLVER

        try {
            this.setVisible(false);
            Controladora.abrirMenu2();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jBvolverActionPerformed

    private void jBcomprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcomprarActionPerformed
        // BOTON COMPRAR
        try {

            //COMPROBACION QUE LOS CAMPOS INTRODUCIDOS NO ESTEN VACIOS
            if (jTproducto.getText().isEmpty() || jTunidades.getText().isEmpty() || jTimporte.getText().isEmpty()) {
                //MENSAJES DE ALERTA VARIOS
                jLfallo.setVisible(true);
                JOptionPane.showMessageDialog(this, "Los campos son obligatorios");
                jLfallo.setVisible(false);

            } else {
                /*SI LOS CAMPOS TIENEN UN VALOR REAL Y LA COMPRA SE PUEDE EFECTUAR
                LE PIDO A LA CONTROLADORA QUE ME RECALCULE LOS PRODUCTOS QUE TENIA 
                MENOS LOS ADQUIRIDOS Y ME DIGA QUE LA COMPRA HA SIDO EFECTUADA*/
                Controladora.recalcularUnidadesDisponibles(jTunidades.getText());
                //AVISOS VARIOS
                jLok.setVisible(true);
                JOptionPane.showMessageDialog(this, "Productos Vendidos.");
                //RESETEO LOS CAMPOS PARA VOLVER A REALIZAR UNA VENTA SI SE PROCEDE
                resetearCampos();

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error desconocido al vender");
        }


    }//GEN-LAST:event_jBcomprarActionPerformed

    private void jTimporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTimporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTimporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcomprar;
    private javax.swing.JButton jBvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLfallo;
    private javax.swing.JLabel jLok;
    private javax.swing.JTextField jTimporte;
    private javax.swing.JTextField jTproducto;
    private javax.swing.JTextField jTunidades;
    // End of variables declaration//GEN-END:variables

    // FUNCIONES PROPIAS PARA LA VENTANA
    
    //RESETEAR CAMPOS DE TEXTO
    private void resetearCampos() {
        jTproducto.setText(null);
        jTunidades.setText(null);
        jTimporte.setText(null);
        jLok.setVisible(false);
    }
}
