/**
 * @author 1gdaw09
 */
package Vistas;

//IMPORTS
import Modelo.*;
import Excepciones.*;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tema7_practica4.*;

public class InicioSesion extends javax.swing.JFrame {

    public int contadorFallos = 2;

    public InicioSesion() {
        initComponents();

        //ESTADOS PREVIOS DE LA VENTANA
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        jTuser.setEnabled(false);
        jPass.setEnabled(false);
        jRsi.setEnabled(false);
        jRno.setEnabled(false);
        jBiniciar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        condicion = new javax.swing.ButtonGroup();
        jTuser = new javax.swing.JTextField();
        jPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRsi = new javax.swing.JRadioButton();
        jRno = new javax.swing.JRadioButton();
        jBver = new javax.swing.JButton();
        jBiniciar = new javax.swing.JButton();
        jBvolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel1.setText("* Usuario:");

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel2.setText("* Contraseña:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("¿Al iniciar sesion aceptas las siguientes condiciones de uso?");

        condicion.add(jRsi);
        jRsi.setText("Sí, acepto");
        jRsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRsiActionPerformed(evt);
            }
        });

        condicion.add(jRno);
        jRno.setText("No acepto");
        jRno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRnoActionPerformed(evt);
            }
        });

        jBver.setText("Ver Condiciones de Uso");
        jBver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBverActionPerformed(evt);
            }
        });

        jBiniciar.setText("Iniciar Sesion");
        jBiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBiniciarActionPerformed(evt);
            }
        });

        jBvolver.setText("Volver al Menu");
        jBvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTuser)
                            .addComponent(jPass))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRsi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRno)))
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBvolver)
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBver)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRsi)
                    .addComponent(jRno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBiniciar)
                    .addComponent(jBvolver))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvolverActionPerformed
        // ACTION BOTON VOLVER
        try {
            if (JOptionPane.showConfirmDialog(this, "¿Esta seguro/a de regresar al Menú Inicio?") == 0) {
                Controladora.volverAlMenuInicio();
                this.dispose();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jBvolverActionPerformed

    private void jBverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBverActionPerformed
        // ACCION BOTON VER CONDICIONES

        if (java.awt.Desktop.isDesktopSupported()) {
            try {
                Desktop dk = Desktop.getDesktop();
                dk.browse(new URI("https://www.sonypictures.com/corp/tos.html"));

            } catch (URISyntaxException | IOException ex) {
                Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jRsi.setEnabled(true);
        jRno.setEnabled(true);


    }//GEN-LAST:event_jBverActionPerformed

    private void jRsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRsiActionPerformed
        // ACCION CLICK SI

        if (jRsi.isSelected()) {
            jBiniciar.setEnabled(true);
            jTuser.setEnabled(true);
            jPass.setEnabled(true);
        }
    }//GEN-LAST:event_jRsiActionPerformed

    private void jBiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBiniciarActionPerformed
        // ACCION INICIO SESION

        try {
            if (contadorFallos == 0) {

                JOptionPane.showMessageDialog(this, "Amenaza XD");
                Controladora.cerrarVentanas();
            }
            if (jTuser.getText().isEmpty() || jPass.getPassword().equals("")) {
                throw new CampoVacio();
            } else {
                int exite = Controladora.comprobarUsuario(jTuser.getText(), jPass.getPassword());
                if (exite == 1) {
                        Controladora.abrirVentanaGestionPersonal(jTuser.getText());
                        
                    } else {
                        JOptionPane.showMessageDialog(this, "El usuario o clave no existen");
                    }
            }

        } catch (CampoVacio cV) {
            JOptionPane.showMessageDialog(this, "Los campos no pueden estar vacios");
            
        } catch (Exception e) {
           
        }
        contadorFallos--;
        System.out.println(contadorFallos);

    }//GEN-LAST:event_jBiniciarActionPerformed

    private void jRnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRnoActionPerformed
        // ACCION CLICK NO

        if (jRno.isSelected()) {
            jBiniciar.setEnabled(false);
            jTuser.setEnabled(false);
            jPass.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Si no aceptas las condiciones de uso"
                    + "\no podras iniciar la sesion. ");
        }
    }//GEN-LAST:event_jRnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup condicion;
    private javax.swing.JButton jBiniciar;
    private javax.swing.JButton jBver;
    private javax.swing.JButton jBvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPass;
    private javax.swing.JRadioButton jRno;
    private javax.swing.JRadioButton jRsi;
    private javax.swing.JTextField jTuser;
    // End of variables declaration//GEN-END:variables
}
