/**
 * @author 1gdaw09
 */

package Vistas;

//IMPORTS
import java.awt.Color;
import javax.swing.JOptionPane;
import tema7_practica4.*;

public class MenuInicio extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicio
     */
    
    public MenuInicio() {
        initComponents();
        
        //ESTADOS PREVIOS DE LA VENTANA
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.getContentPane().setBackground(Color.white);
   
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBinicioSesion = new javax.swing.JButton();
        jBCerrarApp = new javax.swing.JButton();
        jLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBinicioSesion.setText("INICIAR LA SESION");
        jBinicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinicioSesionActionPerformed(evt);
            }
        });

        jBCerrarApp.setText("SALIR DEL PROGRAMA");
        jBCerrarApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarAppActionPerformed(evt);
            }
        });

        jLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/img/sony.PNG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBCerrarApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBinicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLogo)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLogo)
                .addGap(18, 18, 18)
                .addComponent(jBinicioSesion)
                .addGap(18, 18, 18)
                .addComponent(jBCerrarApp)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCerrarAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarAppActionPerformed
        // ACTION BOTON SALIR
        
        try {
            if (JOptionPane.showConfirmDialog(this, "¿Realmente desea cerrar la aplicación?")==0) {
                JOptionPane.showMessageDialog(this, "Que tenga buen día.");
                Controladora.cerrarVentanas();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "¡Error Inexperado!");
        }
        
        
    }//GEN-LAST:event_jBCerrarAppActionPerformed

    private void jBinicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinicioSesionActionPerformed
        // ACTION BOTON VENTANA INICIO SESION
        
        Controladora.abirVentanaInicioSesion();
        this.dispose();
    }//GEN-LAST:event_jBinicioSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCerrarApp;
    private javax.swing.JButton jBinicioSesion;
    private javax.swing.JLabel jLogo;
    // End of variables declaration//GEN-END:variables
}
