package Vistas;

import Controladora.*;
import javax.swing.JOptionPane;

/**
 *
 * @author 1gdaw07
 */
public class VentanaResultados extends javax.swing.JPanel {

    /**
     * Creates new form VentanaResultados
     */
    public VentanaResultados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBmostrarListado = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTmostrar = new javax.swing.JTextArea();

        jLabel1.setText("LISTADO DE PERSONAS");

        jBmostrarListado.setText("MOSTRAR LISTADO");
        jBmostrarListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBmostrarListadoMouseClicked(evt);
            }
        });
        jBmostrarListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmostrarListadoActionPerformed(evt);
            }
        });

        jBsalir.setText("SALIR");
        jBsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBsalirMouseClicked(evt);
            }
        });

        jTmostrar.setColumns(20);
        jTmostrar.setRows(5);
        jScrollPane1.setViewportView(jTmostrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBmostrarListado)
                        .addGap(187, 187, 187)
                        .addComponent(jBsalir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBmostrarListado)
                    .addComponent(jBsalir))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBmostrarListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmostrarListadoActionPerformed
        // BOTON MOSTRAR:

      
    }//GEN-LAST:event_jBmostrarListadoActionPerformed

    private void jBsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBsalirMouseClicked
        // AL CLICKAR EN SALIR
        
        if (JOptionPane.showConfirmDialog(this, "¿Realmente quieres salir del programa?") == 0) {
            Controladora.salirVentanas();
        } 
    }//GEN-LAST:event_jBsalirMouseClicked

    private void jBmostrarListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBmostrarListadoMouseClicked
        // AL CLICKAR BOTON MOSTRAR DATOS
        Controladora.mostrarLasPersonas();
        jTmostrar.setEditable(true);
    }//GEN-LAST:event_jBmostrarListadoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBmostrarListado;
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTmostrar;
    // End of variables declaration//GEN-END:variables
}
