package Vistas;

import javax.swing.JOptionPane;
import practica1_ejer2_versionbuena.*;

public class vMenu extends javax.swing.JFrame {

    /**
     * Creates new form vMenu
     */
    public vMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMarchivo = new javax.swing.JMenu();
        jMsalir = new javax.swing.JMenuItem();
        jMaccion = new javax.swing.JMenu();
        jMcrear = new javax.swing.JMenuItem();
        jMeliminar = new javax.swing.JMenuItem();
        jModificar = new javax.swing.JMenuItem();
        jMbuscar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMarchivo.setText("Archivo");

        jMsalir.setText("Salir");
        jMsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMsalirActionPerformed(evt);
            }
        });
        jMarchivo.add(jMsalir);

        jMenuBar1.add(jMarchivo);

        jMaccion.setText("Acontecimientos");

        jMcrear.setText("Crear Acontecimientos");
        jMcrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMcrearActionPerformed(evt);
            }
        });
        jMaccion.add(jMcrear);

        jMeliminar.setText("Eliminar Acontecimientos");
        jMeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMeliminarActionPerformed(evt);
            }
        });
        jMaccion.add(jMeliminar);

        jModificar.setText("Modificar Acontecimientos");
        jModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModificarActionPerformed(evt);
            }
        });
        jMaccion.add(jModificar);

        jMbuscar.setText("Buscar Acontecimientos");
        jMbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMbuscarActionPerformed(evt);
            }
        });
        jMaccion.add(jMbuscar);

        jMenuBar1.add(jMaccion);

        jMenu3.setText("Persona");

        jMenuItem1.setText("Crear Persona");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMcrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMcrearActionPerformed
        // ACCION CRERAR ENVENTO
        this.dispose();
        Controladora.abrirVentanaCrearAcontecimientos();

    }//GEN-LAST:event_jMcrearActionPerformed

    private void jMsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMsalirActionPerformed
        // ACTION MENU SALIR
        Controladora.cerrarVentanas();
    }//GEN-LAST:event_jMsalirActionPerformed

    private void jMeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMeliminarActionPerformed
        // ACTION ELIMINAR
        this.dispose();
        Controladora.abrirVentanaCrearAcontecimientos();
    }//GEN-LAST:event_jMeliminarActionPerformed

    private void jMbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMbuscarActionPerformed
        // ACTION BUSCAR
        JOptionPane.showMessageDialog(this, "En proceso de construccion");
    }//GEN-LAST:event_jMbuscarActionPerformed

    private void jModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModificarActionPerformed
        // ACTION MODIFICAR
        this.dispose();
        Controladora.abrirVentanaCrearAcontecimientos();
    }//GEN-LAST:event_jModificarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // ACTION CREAR PERSONA
        this.dispose();
        Controladora.abrirVentanaPersona();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMaccion;
    private javax.swing.JMenu jMarchivo;
    private javax.swing.JMenuItem jMbuscar;
    private javax.swing.JMenuItem jMcrear;
    private javax.swing.JMenuItem jMeliminar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jModificar;
    private javax.swing.JMenuItem jMsalir;
    // End of variables declaration//GEN-END:variables
}
