/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import tema7_pract3_ejer2.*;
import Excepciones.*;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author 1gdaw09
 */
public class ZOO extends javax.swing.JFrame {

    /**
     * Creates new form ZOO
     */
    public ZOO() {
        initComponents();
        this.setResizable(rootPaneCheckingEnabled);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.CYAN);

        jPhijo2.setVisible(false);
        jPhijo3.setVisible(false);
        jPhijo4.setVisible(false);

        //CONFIGURACION INICIAL BOTONES
        preconfiguracionInicialBotones();

        preconfiguracionInicialCampos();
    }

    // VARIABLE PARA CONTADOR PANELES HIJOS
    private Integer anadirPanelHijo = 1;
    private Integer quitarPanelHijo = 1;

    private Integer insertarHijo = 1;

    private static char tipoSocios = ' ';

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipoSocio = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jL2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRfamiliar = new javax.swing.JRadioButton();
        jRindividual = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTnombre = new javax.swing.JTextField();
        jTapellidos = new javax.swing.JTextField();
        jTtelefono = new javax.swing.JTextField();
        jTeMail = new javax.swing.JTextField();
        jL3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPhijo1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTnombreHijo1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jCdia1 = new javax.swing.JComboBox<>();
        jCmes1 = new javax.swing.JComboBox<>();
        jCanyo1 = new javax.swing.JComboBox<>();
        jBborrarHijo1 = new javax.swing.JButton();
        jPhijo2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTnombreHijo2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jCdia2 = new javax.swing.JComboBox<>();
        jCmes2 = new javax.swing.JComboBox<>();
        jCanyo2 = new javax.swing.JComboBox<>();
        jBborrarHijo2 = new javax.swing.JButton();
        jPhijo3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTnombreHijo3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jCdia3 = new javax.swing.JComboBox<>();
        jCmes3 = new javax.swing.JComboBox<>();
        jCanyo3 = new javax.swing.JComboBox<>();
        jBborrarHijo3 = new javax.swing.JButton();
        jPhijo4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTnombreHijo4 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jCdia4 = new javax.swing.JComboBox<>();
        jCmes4 = new javax.swing.JComboBox<>();
        jCanyo4 = new javax.swing.JComboBox<>();
        jBborrarHijo4 = new javax.swing.JButton();
        jBnuevoHijo = new javax.swing.JButton();
        jBinscribirse = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jL1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jL2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jL2.setText("* Si, deseo / deseamos hacerme / hacernos socios/s del Aquarium. Cuota de ingreso 15€ ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CATEGORIA:");

        grupoTipoSocio.add(jRfamiliar);
        jRfamiliar.setText("Socio Familiar = 68€");
        jRfamiliar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRfamiliarMouseClicked(evt);
            }
        });
        jRfamiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRfamiliarActionPerformed(evt);
            }
        });

        grupoTipoSocio.add(jRindividual);
        jRindividual.setText("Socio Individual = 32€");
        jRindividual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRindividualMouseClicked(evt);
            }
        });
        jRindividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRindividualActionPerformed(evt);
            }
        });

        jLabel4.setText("NOMBRE");

        jLabel5.setText("APELLIDOS");

        jLabel6.setText("TELEFONO");

        jLabel7.setText("E-MAIL");

        jTnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnombreActionPerformed(evt);
            }
        });

        jTapellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTapellidosActionPerformed(evt);
            }
        });

        jTtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTtelefonoActionPerformed(evt);
            }
        });

        jTeMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTeMailActionPerformed(evt);
            }
        });

        jL3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jL3.setText("* Hijos:   (sólo menores de edad y en categoría familiar)");

        jLabel1.setText("¡ATENCIÓN!. Esta es una hoja de de inscripción de ejemplo, si desea realmente inscribirse ");

        jLabel2.setText("al Aquarium de San Sebastian, pinche en el siguiente enlace:");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        jLabel8.setText("Nombre:");

        jTnombreHijo1.setEnabled(false);
        jTnombreHijo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnombreHijo1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Fecha Nacimiento:");

        jCdia1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jCdia1.setSelectedIndex(-1);

        jCmes1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jCmes1.setSelectedIndex(-1);

        jCanyo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));
        jCanyo1.setSelectedIndex(-1);

        jBborrarHijo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBborrarHijo1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPhijo1Layout = new javax.swing.GroupLayout(jPhijo1);
        jPhijo1.setLayout(jPhijo1Layout);
        jPhijo1Layout.setHorizontalGroup(
            jPhijo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPhijo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTnombreHijo1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jCdia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCmes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCanyo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBborrarHijo1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPhijo1Layout.setVerticalGroup(
            jPhijo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPhijo1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPhijo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBborrarHijo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPhijo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jCdia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCmes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCanyo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTnombreHijo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel15.setText("Nombre:");

        jTnombreHijo2.setEnabled(false);
        jTnombreHijo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnombreHijo2ActionPerformed(evt);
            }
        });

        jLabel16.setText("Fecha Nacimiento:");

        jCdia2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jCdia2.setSelectedIndex(-1);

        jCmes2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jCmes2.setSelectedIndex(-1);

        jCanyo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));
        jCanyo2.setSelectedIndex(-1);

        jBborrarHijo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBborrarHijo2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPhijo2Layout = new javax.swing.GroupLayout(jPhijo2);
        jPhijo2.setLayout(jPhijo2Layout);
        jPhijo2Layout.setHorizontalGroup(
            jPhijo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPhijo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTnombreHijo2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jCdia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCmes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCanyo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBborrarHijo2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPhijo2Layout.setVerticalGroup(
            jPhijo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPhijo2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPhijo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBborrarHijo2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPhijo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jTnombreHijo2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(jCdia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCmes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCanyo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel17.setText("Nombre:");

        jTnombreHijo3.setEnabled(false);
        jTnombreHijo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnombreHijo3ActionPerformed(evt);
            }
        });

        jLabel18.setText("Fecha Nacimiento:");

        jCdia3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jCdia3.setSelectedIndex(-1);

        jCmes3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jCmes3.setSelectedIndex(-1);

        jCanyo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));
        jCanyo3.setSelectedIndex(-1);

        jBborrarHijo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBborrarHijo3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPhijo3Layout = new javax.swing.GroupLayout(jPhijo3);
        jPhijo3.setLayout(jPhijo3Layout);
        jPhijo3Layout.setHorizontalGroup(
            jPhijo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPhijo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTnombreHijo3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jCdia3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCmes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCanyo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBborrarHijo3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPhijo3Layout.setVerticalGroup(
            jPhijo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPhijo3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPhijo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPhijo3Layout.createSequentialGroup()
                        .addComponent(jTnombreHijo3)
                        .addGap(1, 1, 1))
                    .addGroup(jPhijo3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPhijo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBborrarHijo3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPhijo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18)
                                .addComponent(jCdia3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCmes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCanyo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        jLabel19.setText("Nombre:");

        jTnombreHijo4.setEnabled(false);
        jTnombreHijo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnombreHijo4ActionPerformed(evt);
            }
        });

        jLabel20.setText("Fecha Nacimiento:");

        jCdia4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jCdia4.setSelectedIndex(-1);

        jCmes4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jCmes4.setSelectedIndex(-1);

        jCanyo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));
        jCanyo4.setSelectedIndex(-1);

        jBborrarHijo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBborrarHijo4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPhijo4Layout = new javax.swing.GroupLayout(jPhijo4);
        jPhijo4.setLayout(jPhijo4Layout);
        jPhijo4Layout.setHorizontalGroup(
            jPhijo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPhijo4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTnombreHijo4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jCdia4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCmes4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCanyo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBborrarHijo4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPhijo4Layout.setVerticalGroup(
            jPhijo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPhijo4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPhijo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPhijo4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTnombreHijo4))
                    .addComponent(jBborrarHijo4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPhijo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel20)
                        .addComponent(jCdia4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCmes4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCanyo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPhijo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPhijo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPhijo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPhijo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPhijo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPhijo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPhijo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPhijo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBnuevoHijo.setBackground(new java.awt.Color(51, 204, 0));
        jBnuevoHijo.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jBnuevoHijo.setText("AÑADIR HIJO");
        jBnuevoHijo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBnuevoHijoMouseClicked(evt);
            }
        });
        jBnuevoHijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoHijoActionPerformed(evt);
            }
        });

        jBinscribirse.setBackground(new java.awt.Color(0, 204, 204));
        jBinscribirse.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jBinscribirse.setText("INSCRIBIRSE");
        jBinscribirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinscribirseActionPerformed(evt);
            }
        });

        jLabel10.setText(" Aquarium de San Sebastian");
        jLabel10.setToolTipText("Abrir Enlace");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBnuevoHijo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel10))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(262, 262, 262)
                            .addComponent(jBinscribirse))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(121, 121, 121)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                            .addComponent(jTapellidos)
                                            .addComponent(jTtelefono)
                                            .addComponent(jTeMail)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jRfamiliar)
                                        .addGap(32, 32, 32)
                                        .addComponent(jRindividual)))
                                .addGap(30, 30, 30))
                            .addComponent(jL2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jL3, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jRfamiliar)
                    .addComponent(jRindividual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTeMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jL3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBnuevoHijo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBinscribirse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addGap(5, 5, 5))
        );

        jL1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jL1.setText("HOJA DE INSCRIPCION");
        jL1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTnombreHijo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnombreHijo1ActionPerformed
        // INTRODUCIR NOMBRE HIJO 1 
        try {
            if (jTnombreHijo1.getText().isEmpty()) {
                throw new CampoVacio();
            } else {
                // PASO A METER DIA HIJO 1
                jCdia1.requestFocus();
            }
        } catch (CampoVacio CV) {
            JOptionPane.showMessageDialog(this, "El NOMBRE de tu 1er hijo es obligatorio.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error desconocido");
        }
    }//GEN-LAST:event_jTnombreHijo1ActionPerformed

    private void jTnombreHijo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnombreHijo2ActionPerformed
        // INTRODUCIR NOMBRE HIJO 2
        try {
            if (jTnombreHijo2.getText().isEmpty()) {
                throw new CampoVacio();
            } else {
                // PASO A METER DIA HIJO 2
                jCdia2.requestFocus();
            }
        } catch (CampoVacio CV) {
            JOptionPane.showMessageDialog(this, "El NOMBRE de tu 2º hijo es obligatorio.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error desconocido");
        }
    }//GEN-LAST:event_jTnombreHijo2ActionPerformed

    private void jTnombreHijo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnombreHijo3ActionPerformed
        // INTRODUCIR NOMBRE HIJO 3

        try {
            if (jTnombreHijo3.getText().isEmpty()) {
                throw new CampoVacio();
            } else {
                // PASO A METER DIA HIJO 3
                jCdia3.requestFocus();
            }
        } catch (CampoVacio CV) {
            JOptionPane.showMessageDialog(this, "El NOMBRE de tu 3er hijo es obligatorio.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error desconocido");
        }
    }//GEN-LAST:event_jTnombreHijo3ActionPerformed

    private void jTnombreHijo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnombreHijo4ActionPerformed
        // INTRODUCIR NOMBRE HIJO 4

        try {
            if (jTnombreHijo4.getText().isEmpty()) {
                throw new CampoVacio();
            } else {
                // PASO A METER DIA HIJO 4
                jCdia4.requestFocus();
            }
        } catch (CampoVacio CV) {
            JOptionPane.showMessageDialog(this, "El NOMBRE de tu 4º hijo es obligatorio.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error desconocido");
        }
    }//GEN-LAST:event_jTnombreHijo4ActionPerformed

    private void jRfamiliarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRfamiliarMouseClicked
        // AL CLICKAR BOTON FAMILIAR

        if (jRfamiliar.isSelected()) {
            modoFamiliar();
            jBinscribirse.setEnabled(true);
        }
    }//GEN-LAST:event_jRfamiliarMouseClicked

    private void jRindividualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRindividualMouseClicked
        // AL CLICKAR BOTON INDIVIDUAL

        if (jRindividual.isSelected()) {
            modoIndividual();
            jBinscribirse.setEnabled(true);
        }
    }//GEN-LAST:event_jRindividualMouseClicked

    private void jTnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnombreActionPerformed
        // ENTER NOMBRE

        try {

            if (jTnombre.getText().isEmpty()) {
                throw new CampoVacio();
            }
            jTapellidos.setEnabled(true);
            jTapellidos.requestFocus();
        } catch (CampoVacio CV) {
            JOptionPane.showMessageDialog(this, "El campo NOMBRE es obligatorio");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error desconocido");
        }

    }//GEN-LAST:event_jTnombreActionPerformed

    private void jTapellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTapellidosActionPerformed
        // ENTER APELLIDOS

        try {

            if (jTapellidos.getText().isEmpty()) {
                throw new CampoVacio();
            }
            jTtelefono.setEnabled(true);
            jTtelefono.requestFocus();
        } catch (CampoVacio CV) {
            JOptionPane.showMessageDialog(this, "El campo APELLIDOS es obligatorio.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error desconocido");
        }
    }//GEN-LAST:event_jTapellidosActionPerformed

    private void jTtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTtelefonoActionPerformed
        // ENTER TELEFONO

        try {

            if (jTtelefono.getText().isEmpty()) {
                throw new CampoVacio();
            }

            //VALIDO EL NUMERO DE TELEFONO
            Pattern pat = Pattern.compile("[0-9]{9}");
            Matcher mat = pat.matcher(jTtelefono.getText());

            //SI CUMPLE EL PATRON
            if (mat.find() == true) {
                jTeMail.setEnabled(true);
                jTeMail.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Lo siento el TELEFONO introducido no es valido. \n"
                        + "Solo numeros y como maximo 9 digitos. \n"
                        + "Ejemplo: 902202122 o 646456789.");
                jTtelefono.setText("");
            }

        } catch (CampoVacio CV) {
            JOptionPane.showMessageDialog(this, "El campo TELEFONO es obligatorio.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error desconocido");
        }

    }//GEN-LAST:event_jTtelefonoActionPerformed

    private void jTeMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTeMailActionPerformed
        // ENTER EMAIL

        try {

            if (jTeMail.getText().isEmpty()) {
                throw new CampoVacio();
            }

            //VALIDO EMAIL
            Pattern pat = Pattern.compile("^[_a-z0-9-]+(.[_a-z0-9-]+)*@[a-z0-9-]+(.[a-z0-9-]+)*(.[a-z]{2,4})$");
            Matcher mat = pat.matcher(jTeMail.getText());

            //SI CUMPLE EL PATRON
            if (mat.find() == true) {
                jTnombreHijo1.setEnabled(true);
                jTnombreHijo1.requestFocus();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Lo siento el EMAIL introducido no es valido.\n"
                        + "Has de cumplir con el siguiente patron:\n"
                        + "nombrecorreo@nombreproveedor.dominio");
                jTeMail.setText("");
            }
        } catch (CampoVacio CV) {
            JOptionPane.showMessageDialog(this, "El campo EMAIL es obligatorio");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error desconocido");
        }

    }//GEN-LAST:event_jTeMailActionPerformed

    private void jBnuevoHijoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBnuevoHijoMouseClicked
        // CLICK AÑADIR HIJOS

        validaDatosHijos();

    }//GEN-LAST:event_jBnuevoHijoMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // CLICK LINK

        if (java.awt.Desktop.isDesktopSupported()) {
            try {
                Desktop dk = Desktop.getDesktop();
                dk.browse(new URI("http://aquariumss.com/Tarifas"));

                throw new AvisoGenerarLink();

            } catch (AvisoGenerarLink PGL) {
                System.out.println("GenerandoLink");
            } catch (URISyntaxException | IOException ex) {
                Logger.getLogger(ZOO.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jBborrarHijo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBborrarHijo1MouseClicked
        // CLICK ELIMINAR HIJO 1

        jTnombreHijo1.setText(null);
        //INICIAL DATOS COMBO A SIN VALOR
        jCdia1.setSelectedIndex(-1);
        jCmes1.setSelectedIndex(-1);
        jCanyo1.setSelectedIndex(-1);

    }//GEN-LAST:event_jBborrarHijo1MouseClicked

    private void jBborrarHijo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBborrarHijo2MouseClicked
        // CLICK ELIMINAR HIJO 2
        quitaHijos();

        //RESETEAR VALORES
        jTnombreHijo2.setText(null);
        jCdia2.setSelectedIndex(-1);
        jCmes2.setSelectedIndex(-1);
        jCanyo2.setSelectedIndex(-1);
    }//GEN-LAST:event_jBborrarHijo2MouseClicked

    private void jBborrarHijo3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBborrarHijo3MouseClicked
        // CLICK ELIMINAR HIJO 3

        quitaHijos();

        //RESETEAR VALORES
        jTnombreHijo3.setText(null);
        jCdia3.setSelectedIndex(-1);
        jCmes3.setSelectedIndex(-1);
        jCanyo3.setSelectedIndex(-1);
    }//GEN-LAST:event_jBborrarHijo3MouseClicked

    private void jBborrarHijo4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBborrarHijo4MouseClicked
        // CLICK ELIMINAR HIJO 4
        quitaHijos();

        //RESETEAR VALORES
        jTnombreHijo4.setText(null);
        jCdia4.setSelectedIndex(-1);
        jCmes4.setSelectedIndex(-1);
        jCanyo4.setSelectedIndex(-1);
    }//GEN-LAST:event_jBborrarHijo4MouseClicked

    private void jBinscribirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinscribirseActionPerformed
        // BOTON INSCRIBIRSE

        try {

            if (tipoSocios == 'f') {
                
                Controladora.crearHijos(jTnombreHijo1.getText(), jCdia1.getSelectedItem().toString(), jCmes1.getSelectedItem().toString(), jCanyo1.getSelectedItem().toString());
                
                    
                if (jTnombreHijo4.getText().length() > 1) {
                    Controladora.crearHijos(jTnombreHijo2.getText(), jCdia2.getSelectedItem().toString(), jCmes2.getSelectedItem().toString(), jCanyo2.getSelectedItem().toString());
                }

                if (jTnombreHijo4.getText().length() > 1) {
                    Controladora.crearHijos(jTnombreHijo3.getText(), jCdia3.getSelectedItem().toString(), jCmes3.getSelectedItem().toString(), jCanyo3.getSelectedItem().toString());
                }

                if (jTnombreHijo4.getText().length() > 1) {
                    Controladora.crearHijos(jTnombreHijo4.getText(), jCdia4.getSelectedItem().toString(), jCmes4.getSelectedItem().toString(), jCanyo4.getSelectedItem().toString());
                }

                Controladora.guardarDatos(tipoSocios, jTnombre.getText(), jTapellidos.getText(), jTtelefono.getText(), jTeMail.getText());

                throw new TipoDeSocioNoEspecificado();
                
            } else if (tipoSocios == 'i') {

                Controladora.guardarDatos(tipoSocios, jTnombre.getText(), jTapellidos.getText(), jTtelefono.getText(), jTeMail.getText());
                
                throw new TipoDeSocioNoEspecificado();
            }

        } catch (TipoDeSocioNoEspecificado TDSNE) {
            JOptionPane.showMessageDialog(this, "Selecciona un tipo de SOCIO al inicio.");
        }
    }//GEN-LAST:event_jBinscribirseActionPerformed

    private void jRfamiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRfamiliarActionPerformed
        // ENTER FAMILIAR

        tipoSocios = 'f';

    // jRfamiliar.isSelected()

    }//GEN-LAST:event_jRfamiliarActionPerformed

    private void jRindividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRindividualActionPerformed
        // ENTER INDIVIDUAL

        tipoSocios = 'i';
    }//GEN-LAST:event_jRindividualActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // BOTON MAGICO
        Controladora.mostrarDatos();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jBnuevoHijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoHijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBnuevoHijoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZOO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoTipoSocio;
    private javax.swing.JButton jBborrarHijo1;
    private javax.swing.JButton jBborrarHijo2;
    private javax.swing.JButton jBborrarHijo3;
    private javax.swing.JButton jBborrarHijo4;
    private javax.swing.JButton jBinscribirse;
    private javax.swing.JButton jBnuevoHijo;
    private javax.swing.JComboBox<String> jCanyo1;
    private javax.swing.JComboBox<String> jCanyo2;
    private javax.swing.JComboBox<String> jCanyo3;
    private javax.swing.JComboBox<String> jCanyo4;
    private javax.swing.JComboBox<String> jCdia1;
    private javax.swing.JComboBox<String> jCdia2;
    private javax.swing.JComboBox<String> jCdia3;
    private javax.swing.JComboBox<String> jCdia4;
    private javax.swing.JComboBox<String> jCmes1;
    private javax.swing.JComboBox<String> jCmes2;
    private javax.swing.JComboBox<String> jCmes3;
    private javax.swing.JComboBox<String> jCmes4;
    private javax.swing.JLabel jL1;
    private javax.swing.JLabel jL2;
    private javax.swing.JLabel jL3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPhijo1;
    private javax.swing.JPanel jPhijo2;
    private javax.swing.JPanel jPhijo3;
    private javax.swing.JPanel jPhijo4;
    private javax.swing.JRadioButton jRfamiliar;
    private javax.swing.JRadioButton jRindividual;
    private javax.swing.JTextField jTapellidos;
    private javax.swing.JTextField jTeMail;
    private javax.swing.JTextField jTnombre;
    private javax.swing.JTextField jTnombreHijo1;
    private javax.swing.JTextField jTnombreHijo2;
    private javax.swing.JTextField jTnombreHijo3;
    private javax.swing.JTextField jTnombreHijo4;
    private javax.swing.JTextField jTtelefono;
    // End of variables declaration//GEN-END:variables

    //FUNCIONES PROPIAS DE LA VENTANA
    public void preconfiguracionInicialBotones() {
        jPanel2.setVisible(false);
        jBnuevoHijo.setVisible(false);
        jBinscribirse.setEnabled(false);
    }

    public void preconfiguracionInicialCampos() {
        jTnombre.setEnabled(false);
        jTapellidos.setEnabled(false);
        jTtelefono.setEnabled(false);
        jTeMail.setEnabled(false);
    }

    public void modoFamiliar() {
        jTnombre.setEnabled(true);
        jPanel2.setVisible(true);

        jPhijo1.setEnabled(true);

        jBnuevoHijo.setVisible(true);

        jTnombre.setText(null);
        jTapellidos.setText(null);
        jTtelefono.setText(null);
        jTeMail.setText(null);
    }

    public void modoIndividual() {
        jTnombre.setEnabled(true);
        jPanel2.setVisible(false);
        jBnuevoHijo.setVisible(false);

        jTnombre.setText(null);
        jTapellidos.setText(null);
        jTtelefono.setText(null);
        jTeMail.setText(null);

        jTapellidos.setEnabled(false);
        jTtelefono.setEnabled(false);
        jTeMail.setEnabled(false);
    }

    public void añadeHijos() {

        if (null != anadirPanelHijo) {
            switch (anadirPanelHijo) {
                case 1:
                    jPhijo2.setVisible(true);
                    jTnombreHijo2.setEnabled(true);
                    anadirPanelHijo = anadirPanelHijo + 1;
                    break;
                case 2:
                    jPhijo3.setVisible(true);
                    jTnombreHijo3.setEnabled(true);
                    anadirPanelHijo += 1;
                    break;
                case 3:
                    jPhijo4.setVisible(true);
                    jTnombreHijo4.setEnabled(true);
                    anadirPanelHijo += 1;
                    break;
                default:
                    break;
            }
        }
    }

    public void quitaHijos() {
        if (null != quitarPanelHijo) {
            switch (quitarPanelHijo) {
                case 1:
                    jPhijo4.setVisible(false);
                    jTnombreHijo4.setEnabled(false);
                    quitarPanelHijo = quitarPanelHijo + 1;
                    break;
                case 2:
                    jPhijo3.setVisible(false);
                    jTnombreHijo3.setEnabled(false);
                    quitarPanelHijo = quitarPanelHijo + 1;
                    break;
                case 3:
                    jPhijo2.setVisible(false);
                    jTnombreHijo2.setEnabled(false);
                    quitarPanelHijo = quitarPanelHijo + 1;
                    break;
                default:
                    break;
            }
        }
    }

    public void validaDatosHijos() {
        try {

            if (null != insertarHijo) {
                switch (insertarHijo) {

                    case 1:

                        if (jTnombreHijo1.getText().isEmpty() || jCdia1.getSelectedIndex() == -1 || jCmes1.getSelectedIndex() == -1 || jCanyo1.getSelectedIndex() == -1) {
                            throw new DatosHijosNoValidos();
                        } else {
                            Controladora.crearHijos(jTnombreHijo1.getText().toString(), jCdia1.getSelectedItem().toString(), jCmes1.getSelectedItem().toString(), jCanyo1.getSelectedItem().toString());
                            añadeHijos();

                        }

                        break;
                    case 2:
                        jPhijo3.setVisible(false);
                        jTnombreHijo3.setEnabled(false);
                        quitarPanelHijo = quitarPanelHijo + 1;
                        break;
                    case 3:
                        jPhijo2.setVisible(false);
                        jTnombreHijo2.setEnabled(false);
                        quitarPanelHijo = quitarPanelHijo + 1;
                        break;
                    default:
                        break;
                }
            }

            if (jTnombreHijo1.getText().isEmpty() || jCdia1.getSelectedIndex() == -1 || jCmes1.getSelectedIndex() == -1 || jCanyo1.getSelectedIndex() == -1) {
                throw new DatosHijosNoValidos();
            }

            /*
            if (jBborrarHijo1.getText().isEmpty() || jCdia1.getSelectedIndex() == -1 || jCmes1.getSelectedIndex() == -1 || jCanyo1.getSelectedIndex() == -1) {
                throw new DatosHijosNoValidos();
            } else {
                añadeHijos();
            }
            if (jBborrarHijo2.getText().isEmpty() || jCdia2.getSelectedIndex() == -1 || jCmes2.getSelectedIndex() == -1 || jCanyo2.getSelectedIndex() == -1) {
                throw new DatosHijosNoValidos();
            } else {
                añadeHijos();
            }
            if (jBborrarHijo3.getText().isEmpty() || jCdia3.getSelectedIndex() == -1 || jCmes3.getSelectedIndex() == -1 || jCanyo3.getSelectedIndex() == -1) {
                throw new DatosHijosNoValidos();
            } else {
                añadeHijos();
            }
            if (jBborrarHijo4.getText().isEmpty() || jCdia4.getSelectedIndex() == -1 || jCmes4.getSelectedIndex() == -1 || jCanyo4.getSelectedIndex() == -1) {
                throw new DatosHijosNoValidos();
            } else {
                añadeHijos();
            }
             */
            añadeHijos();
        } catch (DatosHijosNoValidos DHNV) {
            JOptionPane.showMessageDialog(this, "Alguno de los campos de los HIJOS\n"
                    + "no se ha rellenado correctamente.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error desconocido");
        }
    }
}
