package Vistas;



/**
 *
 * @author 1gdaw09
 */
public class vPrincipal extends javax.swing.JFrame {
    
//ABOGADO
    private static vAbogadoInsertar vAI;
    private static vAbogadoBorrar vAB;
    private static vAbogadoEditar vAE;
    private static vAbogadoConsultar vAC;
    
    //CLIENTE
    private static vClienteInsertar vCI;
    private static vClienteBorrar vCB;
    private static vClienteEditar vCE;
    private static vClienteConsultar vCC;

    /**
     * Creates new form vPrincipal
     */
    public vPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        abogados = new javax.swing.JMenu();
        altaAbogado = new javax.swing.JMenuItem();
        BorrarAbogado = new javax.swing.JMenuItem();
        editarAbogado = new javax.swing.JMenuItem();
        consultarAbogado = new javax.swing.JMenuItem();
        casos = new javax.swing.JMenu();
        altaCaso = new javax.swing.JMenuItem();
        closeCaso = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        clientes = new javax.swing.JMenu();
        altaCliente = new javax.swing.JMenuItem();
        bajaCliente = new javax.swing.JMenuItem();
        editarCliente = new javax.swing.JMenuItem();
        consultarCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        archivo.setText("Archivo");
        jMenuBar1.add(archivo);

        abogados.setText("Abogados");

        altaAbogado.setText("Dar de Alta Abogado");
        altaAbogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaAbogadoActionPerformed(evt);
            }
        });
        abogados.add(altaAbogado);

        BorrarAbogado.setText("Dar de Baja Abogado");
        BorrarAbogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarAbogadoActionPerformed(evt);
            }
        });
        abogados.add(BorrarAbogado);

        editarAbogado.setText("Editar Datos Abogado");
        editarAbogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarAbogadoActionPerformed(evt);
            }
        });
        abogados.add(editarAbogado);

        consultarAbogado.setText("Consultar Abogados");
        consultarAbogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarAbogadoActionPerformed(evt);
            }
        });
        abogados.add(consultarAbogado);

        jMenuBar1.add(abogados);

        casos.setText("Casos");

        altaCaso.setText("Dar de Alta Caso");
        casos.add(altaCaso);

        closeCaso.setText("Cerrar Caso");
        casos.add(closeCaso);

        jMenuItem1.setText("Borrar Caso");
        casos.add(jMenuItem1);

        jMenuBar1.add(casos);

        clientes.setText("Clientes");

        altaCliente.setText("Dar de Alta Cliente");
        altaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaClienteActionPerformed(evt);
            }
        });
        clientes.add(altaCliente);

        bajaCliente.setText("Dar de Baja Cliente");
        bajaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaClienteActionPerformed(evt);
            }
        });
        clientes.add(bajaCliente);

        editarCliente.setText("Editar Datos Cliente");
        editarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarClienteActionPerformed(evt);
            }
        });
        clientes.add(editarCliente);

        consultarCliente.setText("Consultar Clientes");
        consultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarClienteActionPerformed(evt);
            }
        });
        clientes.add(consultarCliente);

        jMenuBar1.add(clientes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altaAbogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaAbogadoActionPerformed
        // ACTION ALTA ABOGADO
        vAI = new vAbogadoInsertar();
        vAI.setVisible(true);
    }//GEN-LAST:event_altaAbogadoActionPerformed

    private void editarAbogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarAbogadoActionPerformed
        // ACTION EDITAR ABOGADO
        vAE = new vAbogadoEditar();
        vAE.setVisible(true);
    }//GEN-LAST:event_editarAbogadoActionPerformed

    private void consultarAbogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarAbogadoActionPerformed
        // ACTION CONSULTAR ABOGADO
        vAC = new vAbogadoConsultar();
        vAC.setVisible(true);
    }//GEN-LAST:event_consultarAbogadoActionPerformed

    private void BorrarAbogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarAbogadoActionPerformed
        // ACTION BORRAR ABOGADO
        vAB = new vAbogadoBorrar();
        vAB.setVisible(true);
    }//GEN-LAST:event_BorrarAbogadoActionPerformed

    private void altaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaClienteActionPerformed
        // ACTION ALTA CLIENTE
        vCI = new vClienteInsertar();
        vCI.setVisible(true);
    }//GEN-LAST:event_altaClienteActionPerformed

    private void bajaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaClienteActionPerformed
        // ACTION BAJA CLIENTE
        vCB = new vClienteBorrar();
        vCB.setVisible(true);
    }//GEN-LAST:event_bajaClienteActionPerformed

    private void editarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarClienteActionPerformed
        // ACTION EDITAR CLIENTE
        vCE = new vClienteEditar();
        vCE.setVisible(true);
    }//GEN-LAST:event_editarClienteActionPerformed

    private void consultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarClienteActionPerformed
        // ACTION CONSULTAR CLIENTE
        vCC = new vClienteConsultar();
        vCC.setVisible(true);
    }//GEN-LAST:event_consultarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BorrarAbogado;
    private javax.swing.JMenu abogados;
    private javax.swing.JMenuItem altaAbogado;
    private javax.swing.JMenuItem altaCaso;
    private javax.swing.JMenuItem altaCliente;
    private javax.swing.JMenu archivo;
    private javax.swing.JMenuItem bajaCliente;
    private javax.swing.JMenu casos;
    private javax.swing.JMenu clientes;
    private javax.swing.JMenuItem closeCaso;
    private javax.swing.JMenuItem consultarAbogado;
    private javax.swing.JMenuItem consultarCliente;
    private javax.swing.JMenuItem editarAbogado;
    private javax.swing.JMenuItem editarCliente;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
